### PR TITLE
try adopting taiki-e/cargo-llvm-cov#141 for better reports

### PR DESCRIPTION
**Pull request by ruifengx**
Coverage dropped drastically (~90% to ~25%) after Nov 30, 2021, but the code was not modified at all. It is only possible due to the change in either `rustc` or `cargo-llvm-cov`. Let's first try to downgrade the easy one and see what's going on.

### CODE REVIEW

**Comment by ruifengx** [comment]
Apparently the result doesn't seem right, either. Let's try the fix taiki-e/cargo-llvm-cov#141.

**Comment by ruifengx** [comment]
Looks good, gonna merge this.

This would be a temporary fix: come back at this when the upstream PR is merged.

**Comment by taiki-e** [comment]
FYI, I've just published cargo-llvm-cov 0.3.0 which includes taiki-e/cargo-llvm-cov#141.

**Comment by Krantz-XRF** [comment]
> FYI, I've just published cargo-llvm-cov 0.3.0 which includes taiki-e/cargo-llvm-cov#141.

Wow, thanks for your effort and for letting me know of the new version. I'll definitely try out the new version and transition my CI script to it soon.

**Pull request merged**
